name: justice_chain

description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State management, local vault, ML inference, and live PCM audio capture.
  signals_flutter: ^6.3.0
  hive_flutter: ^1.1.0
  tflite_flutter: ^0.11.0
  record: ^6.2.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3

  # Debugging & Camera
  logger: ^2.4.0
  camera: ^0.10.5

  # Cryptography & Hashing
  crypto: ^3.0.7
  cryptography: ^2.9.0
  flutter_secure_storage: ^11.2.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Offline Mesh & Connectivity
  nearby_connections: ^4.3.0
  connectivity_plus: ^6.1.3

  # QR Code Scanning & Generation
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.0

  http: ^1.6.0
  flutter_dotenv: ^6.0.1
  video_player: ^2.11.1
  web3dart: ^3.0.3
  wallet: ^0.0.18

  # NEW: Offline P2P Networking

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/distress_model.tflite
    - assets/models/labels.txt
    - .env